#!/bin/bash -e
set -o pipefail

SWD=$(realpath -e "${0%/*}")
PATH=$SWD:${SWD%/*/*}:$PATH

agent='Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0'

text=${*:-$([[ -t 0 ]]||ifne cat)}
text=${text:?}

# NOTE:(limitation) src|dst must be Japanese!
sl=JA
tl=EN
path=english_japanese

url="http://www.excite.co.jp/world/"
url+="$path/"

tos-limit-speed 100 1 <<< "$text"

# auto_detect_flg:   1
# swb_lp:            JAEN
exec curl -s \
  -H 'Host: www.excite.co.jp' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Accept-Languages: en-US,en' \
  -A "$agent" -G "$url" \
  --data-urlencode "wb_lp=${sl}${tl}" \
  --data-urlencode "before_lang=${sl}" \
  --data-urlencode "after_lang=${tl}" \
  --data-urlencode "auto_detect=off" \
  --data-urlencode "before=$text" \
| gzip -dc --force \
| sed -rn '
  /^.*<textarea.* name="after".*>(.*)<\/textarea>$/{
    s//\1/
    s/&quot;/"/g
    s/&lt;/</g
    s/&gt;/>/g
    s/&amp;/\&/g
  p;q}
' | { rsp=$(cat)
  echo '{}' | jshon -s "$rsp" -i text -s "$text" -i src -j
}

# NOTE: very slow response (>1.3s) -> TRY batch TL and reconstruct
