#!/usr/bin/perl -w
use strict;
use utf8;
use autodie;
binmode (STDIN, ':utf8');
binmode (STDOUT, ':utf8');
use Data::Dump qw(dump);

# REF http://www.rikai.com/library/kanjitables/kanji_codes.unicode.shtml

my $th = 0;
my %wtbl;

# Sort single phrase parts by origin indexes
sub ipairs($$) { my @p;
    my @words = reverse split(/\s+/, $_[0]);
    my @numbers = $_[1] =~ /\d+/g;

    # FIXED BUG 117:3:19-25 has coords as single word => len @o > len @p
    # FIXED BUG@1 reverse order of words in non-splitted phrases 117:4:6-7,38-41
    # BUG sometimes order isn't inverted! 117:{7,12}:1 (aligned to en-US?)
    #   => Therefore I can't use it directly to split phrases to words!
    # HACK => count symbols w/o spaces in separate elements, then reverse each one
    for(my $i=0, my $j=0; $i < scalar @numbers; $i+=2) {
        my $pos = $numbers[$i];
        my $len = $numbers[$i+1] - $pos;

        my @wrds;
        my $k = $len;
        while($k > 0 and $j < scalar @words) {
            my $w = $words[$j++];
            push @wrds, $w;
            $k -= length $w;
        }

        push @p, [$pos, $len, join("·", @wrds)];
    }
    # ALT map { [$numbers[2*$_], $numbers[2*$_+1] - $numbers[2*$_]] } (0 .. scalar(@numbers)/2-1);
    return sort { $a->[0] <=> $b->[0] } (@p)
}

while(<>) {
    chomp;
    my @p = ipairs($_, <>);
    # print dump(@p),"\n";

    # Find index for main part of phrase
    #   * with kanji
    #   * longest word
    #   * ignore [:punct:] in word's length
    # BAD BUT may provide wrong order
    # ! rarely non-reversed order of words in phrase (rezero:138:{1,2}:1)
    # ! punct glued to words -- wrong rows order (rezero:138:21:1)
    #   :: +trimmed punct by get-wtbl, +non-reversed order

    my ($key, $max) = (65536, -1);
    my @pp = grep { $_->[2] =~ /[\u3400-\u9faf]/ } @p;
    @pp = @p if not @pp;
    foreach (@pp) {
        my $len = length($_->[2] =~ s/[[:punct:]]//gr);
        next if $len <= $max;
        $key = $_->[0];
        $max = $len;
        # print dump($len),"\n";
    }
    # print dump($key,@p),"\n";

    my $s = "";
    my $n = <>; #chomp $n;
    for(my $i=0; $i < $n+0; ++$i) {
        my $w = <>; $_ = <>; chomp;
        $s .= ($i ? ", " : "") . $_ if($w+0 > $th);
    }
    # Don't include lines without meaningful words
    if (@p) {
        my $o = ($s !~ /\w/) ? '-'x10 : join(" ", map { $_->[2] } @p);
        # print dump($o),"\n";
        $wtbl{$key} = $o . "|" . $s;
    }
}

# Sort all phrases by origin indexes of main part
my @wlst = @wtbl{sort {$a <=> $b} keys %wtbl};
# Remove excessive separators
shift @wlst if @wlst and $wlst[0] =~ /^-+\|/;
pop @wlst if @wlst and $wlst[-1] =~ /^-+\|/;
print $_,"\n" foreach (@wlst);
