#!/bin/bash -e
set -o pipefail

# ALT:(with words weight)

jshon -e5 -a -e0 -u -p -e3 -j -p -e2 -l -a -e1 -u -p -e0 -u \
| sed -r '
  /\(aux:relc\)|\(null:pronoun\)/s//·/g
  /^[[:punct:][:blank:]]+(\S)/s//\1/
  /(\S)[[:punct:][:blank:]]+$/s//\1/
'

# NOTE:(·) removed to compare words in phrases and spans
