#!/bin/bash -e
set -o pipefail

text=${*:-$([[ -t 0 ]]||ifne cat)}
text=${text:?}

SWD=$(realpath -e "${0%/*}")
PATH=$SWD:${SWD%/*/*}:$PATH

# agent="Mozilla/5.0 (X11; Linux x86_64)"
agent='Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0'
# agent='Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0'

url="http://translate.googleapis.com/translate_a/single?"
url+="client=gtx"
url+="&sl=ja&tl=en&hl=en"  # &dj=1
# url+="&dt=t&dt=at&dt=rm"  # python
url+="&dt=t&dt=at&dt=rm&dt=bd&source=input"  # source=ls
url+="&tk=$(query-tk "$text")"  # tk has the same left/right ?

# Limit 10k/100s, 1M/1day:
# TODO: On each TL -- print remaining chars for day
tos-limit-speed 100 1 <<< "$text"

# NOTE: python-like
# exec curl -v -s -H 'Accept:' -H 'Accept-Encoding: identity' \
#   -A "$agent" -H 'Connection: close' \
#   -G "$url" --data-urlencode "q=$text" \

# NOTE: gt-ext-like
# BAD: no output with --http2
#   NEED:(--http2) paci nghttp2 curl-http2-git
exec curl -s -H 'Host:' \
  -H 'Accept-Encoding: gzip, deflate, sdch, br' \
  -H 'Accept-Languages: en-US,en;q=0.8' \
  -A "$agent" -G "$url" --data-urlencode "q=$text" \
| gzip -dc | perl -lpe 's/(,|\[)(?=,|\])/$1null/g'

# DEV: peek first char == '[' and exit 1 with empty stdout
# OR: exit if curl header != 200
#   Print rsp code to stderr
#     http://beerpla.net/2010/06/10/how-to-display-just-the-http-response-code-in-cli-curl/

# TODO: find upper limit on CJK text chunk in url: (2000-24-103)/9=208
# More precise count
#   Query escaped url from somewhere
#     https://curl.haxx.se/mail/archive-2007-11/0085.html
#   Dry-run to extract encoded url
#     http://stackoverflow.com/questions/6180162/echo-curl-request-header-body-without-sending-it

# ALT:(translate-shell)
# [[ -f $dfl ]] || trans -verbose -no-theme -no-ansi \
#    -show-languages=n -show-prompt-message=n -indent 8 \
#    -sl ja -tl en -i $sfl -o $dfl
