#!/bin/bash -e
set -o pipefail

cmd=${1:?}
src=${2:?}
fun=${3:?}
dst=${4:?}

PATH=$(realpath -e "${0%/*}"):$PATH

# BAD: ex-map linewise spawning is too slow: user >8s for 400L
# ALT:(one-pass) awk 'BEGIN{print"["} NR>1{printf","} END{print"]"} 1' "$dst" | jshon -a -e0 -a -e1
#   BUT: as -d-1 don't work, we can't discard 'null' and we completely crash on broken json...

{ diff -detw \
  <(ex-map "$fun" < "$dst") \
  <(sed '/^\s\+/s///' "$src") \
  && exit || (($?==1)) || exit
} | ex-atomic | ex-apply "$cmd" "$dst"
