#!/bin/bash -e

url=${1:?}
name=$2

agent="Mozilla/5.0 (X11; Linux x86_64)"

ARGS=( --user-agent "$agent"
  --remote-time
)

# --progress-bar
# --continue-at -
# --user login:paswd

[[ $name ]] \
&& ARGS+=( --create-dirs --output "$name" ) \
|| ARGS+=( --remote-header-name --remote-name )

exec curl "${ARGS[@]}" "${url%/}"
