#!/bin/bash -e
set -o pipefail
trap 'exit 1' INT
trap 'echo >/dev/tty' EXIT

# TODO:SEE: 'column' sources to align wide-char columns

mtl=${1:?}
src=${2:?}
dst=${3:?}

SWD=$(realpath -e "${0%/*}")
PATH=$mtl:$SWD:$PATH

N=$(wc -l < "$src")
n=0

exec > "$dst"

while
  IFS= read -r google <&3
do
  ((n+=1))
  printf "\r%3d%% : %s" "$((100*n/N))" "$n/$N" >/dev/tty

  printf "%04d\n" "$n"
  { printf "* "; get-orig <<< "$google" 3<&- 4<&-; }
  { printf ": "; get-phon <<< "$google" 3<&- 4<&-; }
  { printf "= "; get-tran <<< "$google" 3<&- 4<&-; }
  # TODO: sort wtbl by order of origin (1st index of the longest span)
  #   => attach indexes to get-wtbl, place into array in fmt-wtbl, print in END{}
  get-wtbl <<< "$google" 3<&- 4<&- | fmt-wtbl \
  | column -t -s '|' -o ' | ' | awk '$0="| "$0'
  echo

done 3<"$src"
