#!/bin/bash -e
set -o pipefail
trap 'exit 1' INT
trap 'echo >/dev/tty' EXIT

src=${1:?}
shift

N=$(wc -l < "$src")
n=0

# BAD: progressbar breaks on 'make -j9'

while IFS= read -r line; do ((n+=1))
  printf "\r%3d%% : %s" "$((100*n/N))" "$n/$N" >/dev/tty
  eval "$@" <<< "$line"
done < "$src"
