#!/bin/bash -e
set -o pipefail
trap 'exit 1' INT

src=${1:?}
shift

N=$(wc -l < "$src")
n=1

echo >/dev/tty

while read line; do
  printf "\r%03d%% : %s" "$((100*n/N))" "$n/$N" >/dev/tty
  eval "$@" <<< "$line"
  ((n+=1))
done < "$src"

echo >/dev/tty
