#!/bin/bash -e
set -o pipefail

mtl=${1:?}
src=${2:?}
dst=${3:?}
tmp=${dst}.part

# SWD=$(realpath -e "${0%/*}")
# PATH=$SWD/$mtl:$SWD:$PATH
PATH=$(realpath -e "${0%/*}"):$PATH

[[ -s $dst ]] && mv -fT "$dst" "$tmp"

# DEV:ENH: use ex-sync only on different part, then use '>>' with bar
#   => search last match, then split input for sequent commands
# ALT: use sqlite here, give up on plain text

if [[ -s $tmp ]]; then
  ex-sync "$mtl/query" "$src" "$mtl/get-orig" "$tmp"
else
  map-stdin "$src" "'$mtl/query' >> '$tmp'"
fi

mv -fT "$tmp" "$dst"
touch "$dst"  # Upd time even if no diff

# = Considering x-www-form-urlencoded header there is no need for per-sentence translation
# BUT then all phonetics will be messed up (however words table is possible to split)
# TRY insert another (like '|' or utf-8) delimiter -- to split phonetics
#  - complete mess in sentence splitting
#  - too hard to compare resulting json with src
#  ! you are treated as robot after several dozens of requests
#  - for limited GET request no sense to join multiple sentence
