#!/bin/bash -e
PATH=$(realpath -e "${0%/*}"):$PATH
set -o pipefail

src=${1:?}
dst=${2:?}
tmp=${dst}.part

[[ -s $dst ]] && mv -fT "$dst" "$tmp"

if [[ -s $tmp ]]; then
  ex-sync 'mtl-google' "$src" \
    'jshon -Q -e0 -e0 -e1 -u || echo' "$tmp"
else
  while read line; do
    mtl-google >> "$tmp" <<< "$line"
    printf "." >/dev/tty
  done < "$src"
fi
echo >/dev/tty

mv -fT "$tmp" "$dst"
touch "$dst"  # Upd time even if no diff

# ALT: use sqlite here, give up on plain text
#   => considering x-www-form-urlencoded header there is no need for per-sentence translation
#   => BUT then all phonetics will be messed up (however words table is possible to split)
#     TRY insert another (like '|' or utf-8) delimiter -- to split phonetics

# sed -n '3{p;q}' 001.json |
# TL:  jshon -e0 -e0 -e0 -u
# RAW: jshon -e0 -e0 -e1 -u
# PH:  jshon -e0 -e1 -e3 -u
# WRD: jshon -e5 -a -e0 -u -p -e2 -l -a -e0 -u | awk '{printf"%s",$0;getline;n=$0;while(n-->0){getline;printf"|%s",$0};print""}'
# ALT:(with words weight) jshon -e5 -a -e0 -u -p -e2 -l -a -e0 -u -p -e1 -u
