#!/bin/bash -e
PATH=$(readlink -e "${0%/*}"):$PATH

text=${*:-$([[ -t 0 ]]||ifne cat)}
text=${text:?}

# TODO: choose random agent
# agent="Mozilla/5.0 (X11; Linux x86_64)"
# agent='Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0'
agent='Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0'

# TODO: shuffle path components
url="http://translate.googleapis.com/translate_a/single?"
url+="client=gtx&ie=UTF-8&oe=UTF-8&dt=t&dt=rm&dt=at"
url+="&sl=ja&tl=en&hl=en"
url+="&tk=$(mtl-google-tk "$text")"

# Limit 10k/100s, 1M/1day:
# TODO: On each TL -- print remaining chars for day
# tos-google-min 100 1 <<< "$text"

# TODO: find upper limit on CJK text chunk in url
exec curl -s -A "$agent" "$url" --data-urlencode "q=$text" \
| perl -lpe 's/(,|\[)(?=,|\])/$1null/g'

# ALT:(translate-shell)
# [[ -f $dfl ]] || trans -verbose -no-theme -no-ansi \
#    -show-languages=n -show-prompt-message=n -indent 8 \
#    -sl ja -tl en -i $sfl -o $dfl
