#!/bin/bash -e
# Terms of Service (Times on Sleep)
# Prevent '302 Moved'. Use r.b <(./mtl-google hello)

c=${1:?}    # chars
s=${2:?}    # seconds
n=$(wc -m)  # text len
((n>0)) || exit 0
log=${3:-${LOG:-/tmp/${0##*/}.log}}

if [[ -f $log ]]; then
  t=$(date +%s.%N)
  read pt pn < <(tail -1 "$log")
  dt=$(bc <<< "if(0 < t = $pn * $s / $c + $pt - $t) t")
  # echo $dt >/dev/tty
  [[ -z $dt ]] || sleep $dt
fi

# ALT: get N from 1st line and traverse until N-$3>$c and print time on $0
# N=$(tac "$log" | awk -vt=$(date +%s.%N) -vs=$t \
#   'm=t-$1<s{n+=$2}!m{print n}')

printf "%.3f %d\n" "$(date +%s.%N)" "$n" >> "$log"

# ENH when script executes -- accumulate time/count separately
#   => no need to traverse file at that session then
#   BUT each second many entries expired!
